package main

// `sporo docs` prints this binary's own command surface — every verb, its one-line purpose,
// and its flags — grouped by the taxonomy the package doc describes. Two audiences, one
// source: a human runs `sporo docs` for a readable map, and the site's build runs
// `sporo docs --json` to render the documentation page. Because both derive from the live
// cobra tree, the page can never claim a verb the binary does not have, nor miss one it does
// — the drift a hand-written docs page invites (a changed `Short:`, a new verb) is designed
// out. The JSON is a committed snapshot regenerated by `go generate`; a CI gate reds if the
// snapshot and the tree disagree, which is how the guarantee is kept honest.

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// encodeSurface writes the surface as indented JSON with HTML-escaping OFF, so a `<slug>` in a
// Use string stays `<slug>` and not `<slug>` — the committed snapshot is reviewed as
// a diff, and legible is the point. A trailing newline keeps it a well-formed text file.
func encodeSurface(w io.Writer, s Surface) error {
	enc := json.NewEncoder(w)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	return enc.Encode(s)
}

// FlagDoc is one flag as the docs surface reports it. Shorthand is omitted deliberately:
// this CLI registers only long-form flags (the sole shorthand anywhere is cobra's own -h/-v).
type FlagDoc struct {
	Name    string `json:"name"`
	Default string `json:"default,omitempty"`
	Usage   string `json:"usage"`
}

// VerbDoc is one command. Use is emitted verbatim because it already carries the positional
// argument shape (`export <slug>`); cobra stores Args as an opaque func, so that string is the
// only honest source for "what does this verb take".
type VerbDoc struct {
	Use         string    `json:"use"`
	Name        string    `json:"name"`
	Short       string    `json:"short"`
	Long        string    `json:"long,omitempty"`
	Group       string    `json:"group"`
	Flags       []FlagDoc `json:"flags,omitempty"`
	Subcommands []VerbDoc `json:"subcommands,omitempty"`
}

// Surface is the whole emitted document: the binary version (so the site's JSON-LD cites the
// release it was built from, not a hand-typed number) and every top-level verb.
type Surface struct {
	Version string    `json:"version"`
	Verbs   []VerbDoc `json:"verbs"`
}

// docGroups is the taxonomy the package doc names. Cobra has no grouping of its own, so the
// order and membership live here — the one place a new verb must be placed. `groupOf` treats
// an unplaced verb as "other"; a test asserts that bucket stays empty, which is what turns
// "remember to group the new verb" into a gate.
var docGroups = []struct {
	Key   string
	Title string
	Verbs []string
}{
	{"authoring", "Authoring", []string{"harvest", "new", "lint", "seal", "export", "list", "feedback", "review", "seed"}},
	{"handover", "Handover", []string{"publish", "adopt", "pull", "conform"}},
	{"surface", "Install surface", []string{"init", "update", "genre", "projects", "recipes", "docs"}},
	{"binary", "Binary", []string{"upgrade"}},
}

func groupOf(verb string) string {
	for _, g := range docGroups {
		for _, v := range g.Verbs {
			if v == verb {
				return g.Key
			}
		}
	}
	return "other"
}

// buildSurface walks a FRESH command tree (not the running one) so cobra's auto-added `help`
// and `completion` verbs — attached only during Execute — never leak into the snapshot. The
// walk is deterministic: cobra returns children sorted, and flags are sorted by name. Hidden
// commands are skipped: they are build tools (e.g. `web-mirror`, run only by `go generate`), not
// part of the user-facing surface the docs page documents.
func buildSurface() Surface {
	s := Surface{Version: version}
	for _, c := range root().Commands() {
		if c.Hidden {
			continue
		}
		s.Verbs = append(s.Verbs, verbDoc(c))
	}
	return s
}

func verbDoc(c *cobra.Command) VerbDoc {
	d := VerbDoc{
		Use:   c.Use,
		Name:  c.Name(),
		Short: c.Short,
		Long:  c.Long,
		Group: groupOf(c.Name()),
		Flags: flagsOf(c),
	}
	for _, sub := range c.Commands() {
		if sub.Hidden {
			continue
		}
		d.Subcommands = append(d.Subcommands, verbDoc(sub))
	}
	return d
}

func flagsOf(c *cobra.Command) []FlagDoc {
	var out []FlagDoc
	c.Flags().VisitAll(func(f *pflag.Flag) {
		if f.Name == "help" {
			return
		}
		out = append(out, FlagDoc{Name: f.Name, Default: f.DefValue, Usage: f.Usage})
	})
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// docsCmd prints the surface: `--json` (or `--out`) for the site build, a grouped human map
// otherwise. `--out` writes the JSON snapshot to a file (creating its directory), which is how
// `go generate` refreshes the committed `surface.json` without relying on shell redirection.
func docsCmd() *cobra.Command {
	var asJSON bool
	var out string
	cmd := &cobra.Command{
		Use:   "docs",
		Short: "Print this binary's command surface — the source the docs page is built from",
		RunE: func(cmd *cobra.Command, args []string) error {
			s := buildSurface()
			if out != "" {
				if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
					return err
				}
				f, err := os.Create(out)
				if err != nil {
					return err
				}
				defer f.Close()
				return encodeSurface(f, s)
			}
			if asJSON {
				return encodeSurface(cmd.OutOrStdout(), s)
			}
			w := cmd.OutOrStdout()
			fmt.Fprintf(w, "sporo %s — %d verbs\n", s.Version, len(s.Verbs))
			byGroup := map[string][]VerbDoc{}
			for _, v := range s.Verbs {
				byGroup[v.Group] = append(byGroup[v.Group], v)
			}
			for _, g := range docGroups {
				vs := byGroup[g.Key]
				if len(vs) == 0 {
					continue
				}
				sort.Slice(vs, func(i, j int) bool { return vs[i].Name < vs[j].Name })
				fmt.Fprintf(w, "\n%s\n", g.Title)
				for _, v := range vs {
					fmt.Fprintf(w, "  %-9s %s\n", v.Name, v.Short)
				}
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&asJSON, "json", false, "emit the surface as JSON (what the docs page consumes)")
	cmd.Flags().StringVar(&out, "out", "", "write the JSON snapshot to this file (used by `go generate`)")
	return cmd
}
